// Canonical Good Thoughts footer — same on every section. Generated by shell/build_footers.py from shell/footer-links.json — do not edit by hand; edit the JSON and re-run with --sync.
//
// Plain <a> everywhere (not a router <Link>): these are apex-level routes that
// live outside any single app's client-side router. External links open in a
// new tab.

const GROUPS = [
  {
    "title": "Explore",
    "links": [
      {
        "label": "Finance",
        "href": "/"
      },
      {
        "label": "Markets",
        "href": "/markets"
      },
      {
        "label": "IPO",
        "href": "/ipo"
      },
      {
        "label": "Blog",
        "href": "/blog/"
      },
      {
        "label": "World Monitor",
        "href": "/monitor"
      }
    ]
  },
  {
    "title": "Finance Tools",
    "links": [
      {
        "label": "Screens",
        "href": "/screens"
      },
      {
        "label": "Top Picks",
        "href": "/top-picks"
      },
      {
        "label": "Watchlists",
        "href": "/watchlists"
      },
      {
        "label": "Compare",
        "href": "/compare"
      },
      {
        "label": "Indices",
        "href": "/indices"
      }
    ]
  },
  {
    "title": "IPO",
    "links": [
      {
        "label": "All IPOs",
        "href": "/ipo/full_list"
      },
      {
        "label": "IPO Scorecard",
        "href": "/ipo/tools/ipo-scorecard"
      },
      {
        "label": "Compare IPOs",
        "href": "/ipo/tools/ipo-compare"
      },
      {
        "label": "IPO Guide",
        "href": "/ipo/resources/ipo-guide"
      },
      {
        "label": "Investment Tips",
        "href": "/ipo/resources/investment-tips"
      },
      {
        "label": "FAQ",
        "href": "/ipo/resources/faq"
      }
    ]
  },
  {
    "title": "Government Portals",
    "links": [
      {
        "label": "NFRA",
        "href": "https://nfra.gov.in/"
      },
      {
        "label": "MCA",
        "href": "https://www.mca.gov.in/"
      },
      {
        "label": "NCLAT",
        "href": "https://nclat.nic.in/"
      },
      {
        "label": "NCLT",
        "href": "https://nclt.gov.in/"
      },
      {
        "label": "National Portal of India",
        "href": "https://www.india.gov.in/"
      },
      {
        "label": "MyGov",
        "href": "https://www.mygov.in/"
      },
      {
        "label": "MeitY",
        "href": "https://www.meity.gov.in/"
      },
      {
        "label": "Startup India",
        "href": "https://www.startupindia.gov.in/"
      }
    ]
  },
  {
    "title": "Stock Exchanges",
    "links": [
      {
        "label": "NSE India",
        "href": "https://www.nseindia.com/"
      },
      {
        "label": "BSE India",
        "href": "https://www.bseindia.com/"
      },
      {
        "label": "MCX",
        "href": "https://mcxindia.com/"
      },
      {
        "label": "MSE India",
        "href": "https://www.msei.in/"
      },
      {
        "label": "AMFI",
        "href": "https://www.amfiindia.com/"
      }
    ]
  },
  {
    "title": "Regulators",
    "links": [
      {
        "label": "SEBI",
        "href": "https://www.sebi.gov.in/"
      },
      {
        "label": "RBI",
        "href": "https://www.rbi.org.in/"
      },
      {
        "label": "IRDAI",
        "href": "https://irdai.gov.in/"
      }
    ]
  },
  {
    "title": "Resources",
    "links": [
      {
        "label": "CDSL",
        "href": "https://www.cdslindia.com/"
      },
      {
        "label": "NSDL",
        "href": "https://nsdl.co.in/"
      },
      {
        "label": "World Monitor",
        "href": "/monitor"
      },
      {
        "label": "IPO Tracker",
        "href": "/ipo"
      }
    ]
  }
];

const LEGAL = [
  {
    "label": "About",
    "href": "/about"
  },
  {
    "label": "Contact",
    "href": "/contact"
  },
  {
    "label": "Privacy",
    "href": "/privacy"
  },
  {
    "label": "Terms",
    "href": "/terms"
  },
  {
    "label": "Disclaimer",
    "href": "/disclaimer"
  },
  {
    "label": "Cookies",
    "href": "/cookies"
  },
  {
    "label": "Payment Policy",
    "href": "/payment-policy"
  }
];

const SOCIAL = [
  {
    "label": "Facebook",
    "href": "https://www.facebook.com/goodipos"
  },
  {
    "label": "Twitter",
    "href": "https://twitter.com/goodipos"
  },
  {
    "label": "LinkedIn",
    "href": "https://www.linkedin.com/company/goodipos"
  },
  {
    "label": "Instagram",
    "href": "https://www.instagram.com/goodipos"
  }
];

const linkProps = (href: string) =>
  href.startsWith('http') ? { target: '_blank', rel: 'noopener noreferrer' } : {};

const Footer = () => {
  const year = new Date().getFullYear();
  const link = { fontSize: 12.5, color: '#374b41', textDecoration: 'none' };
  return (
    <footer style={{ borderTop: '1px solid rgba(0,69,50,0.12)', background: '#f6fdf9' }}>
      <style>{`.gt-foot-row{display:grid;grid-template-columns:1fr;gap:4px 16px;padding:7px 0}@media(min-width:640px){.gt-foot-row{grid-template-columns:175px 1fr;align-items:baseline}}.gt-foot-links{display:flex;flex-wrap:wrap;gap:4px 16px}`}</style>
      <div style={{ maxWidth: 1200, margin: '0 auto', padding: '20px 24px 14px' }}>
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px 24px', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 10 }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', alignItems: 'baseline', gap: '2px 14px' }}>
            <span style={{ fontWeight: 700, fontSize: 17, color: '#004532', fontFamily: 'Lora, serif' }}>Good Thoughts</span>
            <span style={{ fontSize: 12.5, color: '#5b6b63' }}>Market data, IPOs, monitoring and editorial content for research — not investment advice.</span>
          </div>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 14px' }}>
            {SOCIAL.map((s) => (
              <a key={s.href} href={s.href} {...linkProps(s.href)} style={{ ...link, fontWeight: 600 }}>{s.label}</a>
            ))}
          </div>
        </div>
        {GROUPS.map((g) => (
          <div key={g.title} className="gt-foot-row" style={{ borderTop: '1px solid rgba(0,69,50,0.08)' }}>
            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: '.06em', textTransform: 'uppercase', color: '#5b6b63' }}>{g.title}</div>
            <div className="gt-foot-links">
              {g.links.map((l) => (
                <a key={l.label + l.href} href={l.href} {...linkProps(l.href)} style={link}>{l.label}</a>
              ))}
            </div>
          </div>
        ))}
        <div style={{ marginTop: 4, paddingTop: 10, borderTop: '1px solid rgba(0,69,50,0.08)', display: 'flex', flexWrap: 'wrap', justifyContent: 'space-between', gap: '6px 24px', alignItems: 'baseline' }}>
          <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px 16px' }}>
            {LEGAL.map((l) => (
              <a key={l.href} href={l.href} {...linkProps(l.href)} style={link}>{l.label}</a>
            ))}
          </div>
          <div style={{ fontSize: 12, color: '#8a9a91' }}>
            © {year} Good Thoughts. All rights reserved. · Built by{' '}
            <a href="https://krakelabsindia.com/" target="_blank" rel="noopener noreferrer" style={{ color: '#374b41', textDecoration: 'none', fontWeight: 600 }}>KLI</a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
